// Planetary data: realistic relative sizes/distances (compressed) and orbital periods
// Real solar system has Neptune ~30 AU and Mercury ~0.4 AU, so we scale distances
// down by a factor for visual sanity but keep relative proportions.
// All speeds are in "radians per second" at the base time-scale and will be
// multiplied by user-controlled speed and frame delta at runtime.

export const SUN_RADIUS = 18;

export const PLANET_DATA = [
  {
    id: 'mercury',
    name: 'Mercury',
    radius: 1.6,
    distance: 32,
    orbitSpeed: 0.48,
    rotationSpeed: 0.012,
    axialTilt: 0.03,
    roughness: 0.95,
    metalness: 0.05,
    textures: { color: 'mercury_color.jpg' },
  },
  {
    id: 'venus',
    name: 'Venus',
    radius: 3.2,
    distance: 48,
    orbitSpeed: 0.35,
    rotationSpeed: -0.006,
    axialTilt: 3.1,
    roughness: 0.85,
    metalness: 0.0,
    textures: { color: 'venus_color.jpg' },
    atmosphere: { color: 0xffb86b, intensity: 1.4, scale: 1.06 },
  },
  {
    id: 'earth',
    name: 'Earth',
    radius: 3.5,
    distance: 68,
    orbitSpeed: 0.3,
    rotationSpeed: 0.02,
    axialTilt: 0.41,
    roughness: 0.75,
    metalness: 0.05,
    textures: {
      color: 'earth_color.jpg',
      normal: 'earth_normal.jpg',
      specular: 'earth_specular.jpg',
      clouds: 'earth_clouds.jpg',
      lights: 'earth_lights.jpg',
    },
    atmosphere: { color: 0x6cb0ff, intensity: 1.2, scale: 1.05 },
    moons: [
      {
        id: 'moon',
        name: 'Moon',
        radius: 0.9,
        orbitDistance: 6,
        orbitSpeed: 1.3,
        rotationSpeed: 0.012,
        axialTilt: 0.12,
        textures: { color: 'moon_color.jpg' },
      },
    ],
  },
  {
    id: 'mars',
    name: 'Mars',
    radius: 2.6,
    distance: 92,
    orbitSpeed: 0.24,
    rotationSpeed: 0.018,
    axialTilt: 0.44,
    roughness: 0.95,
    metalness: 0.0,
    textures: { color: 'mars_color.jpg' },
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    radius: 9.5,
    distance: 132,
    orbitSpeed: 0.13,
    rotationSpeed: 0.045,
    axialTilt: 0.05,
    roughness: 0.6,
    metalness: 0.0,
    textures: { color: 'jupiter_color.jpg' },
  },
  {
    id: 'saturn',
    name: 'Saturn',
    radius: 8.2,
    distance: 175,
    orbitSpeed: 0.09,
    rotationSpeed: 0.038,
    axialTilt: 0.47,
    roughness: 0.7,
    metalness: 0.0,
    textures: { color: 'saturn_color.jpg', ring: 'saturn_ring.png' },
    ring: { innerRadius: 11, outerRadius: 18, segments: 128 },
  },
  {
    id: 'uranus',
    name: 'Uranus',
    radius: 5.4,
    distance: 215,
    orbitSpeed: 0.06,
    rotationSpeed: 0.03,
    axialTilt: 1.71,
    roughness: 0.55,
    metalness: 0.05,
    textures: { color: 'uranus_color.jpg' },
    atmosphere: { color: 0x9be3ff, intensity: 0.8, scale: 1.05 },
  },
  {
    id: 'neptune',
    name: 'Neptune',
    radius: 5.2,
    distance: 252,
    orbitSpeed: 0.04,
    rotationSpeed: 0.032,
    axialTilt: 0.49,
    roughness: 0.5,
    metalness: 0.05,
    textures: { color: 'neptune_color.jpg' },
    atmosphere: { color: 0x4a7bff, intensity: 0.8, scale: 1.05 },
  },
];
