// Planetary data: realistic relative sizes/distances (compressed) and orbital periods.
// Distances are scaled down for visual sanity but relative proportions are kept.
// Speeds are radians/sec at base time-scale and get multiplied by user speed and
// frame delta at runtime. The `info` block is shown in the InfoPanel UI.

export const SUN_RADIUS = 18;

export const SUN_INFO = {
  id: 'sun',
  name: 'Sol',
  type: 'Estrela anã amarela (G2V)',
  radiusKm: '696.340 km',
  mass: '1,989 × 10³⁰ kg',
  temp: '5.500 °C (superfície)',
  funFact: 'Contém 99,86% de toda a massa do Sistema Solar.',
};

export const PLANET_DATA = [
  {
    id: 'mercury',
    name: 'Mercury',
    radius: 1.6,
    distance: 32,
    orbitSpeed: 0.48,
    rotationSpeed: 0.012,
    axialTilt: 0.03,
    roughness: 0.95,
    metalness: 0.05,
    textures: { color: 'mercury_color.jpg' },
    info: {
      type: 'Planeta rochoso',
      radiusKm: '2.440 km',
      mass: '3,30 × 10²³ kg',
      temp: '-173 a 427 °C',
      funFact: 'Um dia solar em Mercúrio dura 176 dias terrestres.',
    },
  },
  {
    id: 'venus',
    name: 'Venus',
    radius: 3.2,
    distance: 48,
    orbitSpeed: 0.35,
    rotationSpeed: -0.006,
    axialTilt: 3.1,
    roughness: 0.85,
    metalness: 0.0,
    textures: { color: 'venus_color.jpg' },
    atmosphere: { color: 0xffb86b, intensity: 1.4, scale: 1.06 },
    info: {
      type: 'Planeta rochoso',
      radiusKm: '6.052 km',
      mass: '4,87 × 10²⁴ kg',
      temp: '465 °C',
      funFact: 'Gira no sentido contrário aos outros planetas.',
    },
  },
  {
    id: 'earth',
    name: 'Earth',
    radius: 3.5,
    distance: 68,
    orbitSpeed: 0.3,
    rotationSpeed: 0.02,
    axialTilt: 0.41,
    roughness: 0.75,
    metalness: 0.05,
    textures: {
      color: 'earth_color.jpg',
      normal: 'earth_normal.jpg',
      specular: 'earth_specular.jpg',
      clouds: 'earth_clouds.jpg',
      lights: 'earth_lights.jpg',
    },
    atmosphere: { color: 0x6cb0ff, intensity: 1.2, scale: 1.05 },
    moons: [
      {
        id: 'moon',
        name: 'Moon',
        radius: 0.9,
        orbitDistance: 6,
        orbitSpeed: 1.3,
        rotationSpeed: 0.012,
        axialTilt: 0.12,
        textures: { color: 'moon_color.jpg' },
      },
    ],
    info: {
      type: 'Planeta rochoso (habitável)',
      radiusKm: '6.371 km',
      mass: '5,97 × 10²⁴ kg',
      temp: '-88 a 58 °C',
      funFact: 'O único lugar conhecido onde a vida existe.',
    },
  },
  {
    id: 'mars',
    name: 'Mars',
    radius: 2.6,
    distance: 92,
    orbitSpeed: 0.24,
    rotationSpeed: 0.018,
    axialTilt: 0.44,
    roughness: 0.95,
    metalness: 0.0,
    textures: { color: 'mars_color.jpg' },
    atmosphere: { color: 0xd97a4a, intensity: 0.55, scale: 1.04 },
    moons: [
      {
        id: 'phobos',
        name: 'Phobos',
        radius: 0.35,
        orbitDistance: 4,
        orbitSpeed: 2.6,
        rotationSpeed: 2.6,
        axialTilt: 0,
        textures: { color: 'moon_color.jpg' },
        tint: 0x8a7a6a,
      },
      {
        id: 'deimos',
        name: 'Deimos',
        radius: 0.25,
        orbitDistance: 5.6,
        orbitSpeed: 1.7,
        rotationSpeed: 1.7,
        axialTilt: 0,
        textures: { color: 'moon_color.jpg' },
        tint: 0x9a8a7a,
      },
    ],
    info: {
      type: 'Planeta rochoso',
      radiusKm: '3.389 km',
      mass: '6,42 × 10²³ kg',
      temp: '-153 a 20 °C',
      funFact: 'Hospeda o Monte Olimpo, o maior vulcão do Sistema Solar.',
    },
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    radius: 9.5,
    distance: 132,
    orbitSpeed: 0.13,
    rotationSpeed: 0.045,
    axialTilt: 0.05,
    roughness: 0.6,
    metalness: 0.0,
    textures: { color: 'jupiter_color.jpg' },
    atmosphere: { color: 0xd8a86a, intensity: 0.6, scale: 1.03 },
    moons: [
      {
        id: 'io',
        name: 'Io',
        radius: 0.7,
        orbitDistance: 13,
        orbitSpeed: 2.4,
        rotationSpeed: 2.4,
        axialTilt: 0,
        textures: { color: 'moon_color.jpg' },
        tint: 0xffe06a,
        emissive: 0x553300,
      },
      {
        id: 'europa',
        name: 'Europa',
        radius: 0.6,
        orbitDistance: 16,
        orbitSpeed: 1.8,
        rotationSpeed: 1.8,
        axialTilt: 0.1,
        textures: { color: 'moon_color.jpg' },
        tint: 0xe8e0d8,
      },
      {
        id: 'ganymede',
        name: 'Ganymede',
        radius: 1.1,
        orbitDistance: 20,
        orbitSpeed: 1.3,
        rotationSpeed: 1.3,
        axialTilt: 0.2,
        textures: { color: 'moon_color.jpg' },
        tint: 0x9a8a7a,
      },
      {
        id: 'callisto',
        name: 'Callisto',
        radius: 1.0,
        orbitDistance: 25,
        orbitSpeed: 0.9,
        rotationSpeed: 0.9,
        axialTilt: 0.1,
        textures: { color: 'moon_color.jpg' },
        tint: 0x6a5a4a,
      },
    ],
    info: {
      type: 'Gigante gasoso',
      radiusKm: '69.911 km',
      mass: '1,90 × 10²⁷ kg',
      temp: '-145 °C',
      funFact: 'A Grande Mancha Vermelha é uma tempestade maior que a Terra.',
    },
  },
  {
    id: 'saturn',
    name: 'Saturn',
    radius: 8.2,
    distance: 175,
    orbitSpeed: 0.09,
    rotationSpeed: 0.038,
    axialTilt: 0.47,
    roughness: 0.7,
    metalness: 0.0,
    textures: { color: 'saturn_color.jpg', ring: 'saturn_ring.png' },
    ring: {
      innerRadius: 11,
      outerRadius: 19,
      segments: 256,
      // Gaps: [start, end] as fraction of (outer-inner)
      gaps: [[0.46, 0.52]], // Cassini division
    },
    atmosphere: { color: 0xe8c88a, intensity: 0.5, scale: 1.03 },
    moons: [
      {
        id: 'titan',
        name: 'Titan',
        radius: 1.2,
        orbitDistance: 24,
        orbitSpeed: 1.0,
        rotationSpeed: 1.0,
        axialTilt: 0,
        textures: { color: 'moon_color.jpg' },
        tint: 0xd9a85a,
        atmosphere: { color: 0xd9a85a, intensity: 1.0, scale: 1.15 },
      },
      {
        id: 'enceladus',
        name: 'Enceladus',
        radius: 0.4,
        orbitDistance: 17,
        orbitSpeed: 1.8,
        rotationSpeed: 1.8,
        axialTilt: 0,
        textures: { color: 'moon_color.jpg' },
        tint: 0xf0f4ff,
        emissive: 0x88aaff,
      },
      {
        id: 'rhea',
        name: 'Rhea',
        radius: 0.55,
        orbitDistance: 20,
        orbitSpeed: 1.4,
        rotationSpeed: 1.4,
        axialTilt: 0,
        textures: { color: 'moon_color.jpg' },
        tint: 0xc8c8c8,
      },
    ],
    info: {
      type: 'Gigante gasoso',
      radiusKm: '58.232 km',
      mass: '5,68 × 10²⁶ kg',
      temp: '-178 °C',
      funFact: 'Tão leve que flutuaria na água, se houvesse um oceano grande o bastante.',
    },
  },
  {
    id: 'uranus',
    name: 'Uranus',
    radius: 5.4,
    distance: 215,
    orbitSpeed: 0.06,
    rotationSpeed: 0.03,
    axialTilt: 1.71,
    roughness: 0.55,
    metalness: 0.05,
    textures: { color: 'uranus_color.jpg' },
    ring: {
      innerRadius: 8,
      outerRadius: 11,
      segments: 128,
      opacity: 0.18,
      color: 0x88aacc,
    },
    atmosphere: { color: 0x9be3ff, intensity: 0.8, scale: 1.05 },
    moons: [
      {
        id: 'miranda',
        name: 'Miranda',
        radius: 0.3,
        orbitDistance: 8,
        orbitSpeed: 1.8,
        rotationSpeed: 1.8,
        axialTilt: 0,
        textures: { color: 'moon_color.jpg' },
        tint: 0xaab0b8,
      },
      {
        id: 'titania',
        name: 'Titania',
        radius: 0.45,
        orbitDistance: 11,
        orbitSpeed: 1.3,
        rotationSpeed: 1.3,
        axialTilt: 0,
        textures: { color: 'moon_color.jpg' },
        tint: 0x9a8a80,
      },
    ],
    info: {
      type: 'Gigante de gelo',
      radiusKm: '25.362 km',
      mass: '8,68 × 10²⁵ kg',
      temp: '-224 °C',
      funFact: 'Gira "de lado", com o eixo quase paralelo ao plano da órbita.',
    },
  },
  {
    id: 'neptune',
    name: 'Neptune',
    radius: 5.2,
    distance: 252,
    orbitSpeed: 0.04,
    rotationSpeed: 0.032,
    axialTilt: 0.49,
    roughness: 0.5,
    metalness: 0.05,
    textures: { color: 'neptune_color.jpg' },
    atmosphere: { color: 0x4a7bff, intensity: 0.9, scale: 1.05 },
    moons: [
      {
        id: 'triton',
        name: 'Triton',
        radius: 0.8,
        orbitDistance: 9,
        orbitSpeed: -1.1, // retrograde
        rotationSpeed: 1.1,
        axialTilt: 0.4,
        textures: { color: 'moon_color.jpg' },
        tint: 0xd8e0e8,
        atmosphere: { color: 0xb8d0ff, intensity: 0.8, scale: 1.2 },
      },
    ],
    info: {
      type: 'Gigante de gelo',
      radiusKm: '24.622 km',
      mass: '1,02 × 10²⁶ kg',
      temp: '-218 °C',
      funFact: 'Os ventos mais rápidos do Sistema Solar passam de 2.000 km/h.',
    },
  },
  {
    id: 'pluto',
    name: 'Pluto',
    radius: 1.0,
    distance: 295,
    orbitSpeed: 0.027,
    rotationSpeed: 0.014,
    axialTilt: 2.1,
    roughness: 0.9,
    metalness: 0.0,
    textures: { color: 'moon_color.jpg' },
    tint: 0xc8a878,
    atmosphere: { color: 0xb8c8ff, intensity: 0.4, scale: 1.1 },
    moons: [
      {
        id: 'charon',
        name: 'Charon',
        radius: 0.5,
        orbitDistance: 3.5,
        orbitSpeed: 1.0,
        rotationSpeed: 1.0,
        axialTilt: 0,
        textures: { color: 'moon_color.jpg' },
        tint: 0xa0a0a0,
      },
    ],
    info: {
      type: 'Planeta anão',
      radiusKm: '1.188 km',
      mass: '1,31 × 10²² kg',
      temp: '-229 °C',
      funFact: 'Reclassificado como planeta anão em 2006.',
    },
  },
  {
    id: 'ceres',
    name: 'Ceres',
    radius: 0.6,
    distance: 115,
    orbitSpeed: 0.21,
    rotationSpeed: 0.016,
    axialTilt: 0.12,
    roughness: 0.95,
    metalness: 0.0,
    textures: { color: 'moon_color.jpg' },
    tint: 0x9a8a78,
    info: {
      type: 'Planeta anão',
      radiusKm: '473 km',
      mass: '9,39 × 10²⁰ kg',
      temp: '-105 °C',
      funFact: 'O maior objeto do cinturão de asteroides.',
    },
  },
  {
    id: 'eris',
    name: 'Eris',
    radius: 1.05,
    distance: 360,
    orbitSpeed: 0.018,
    rotationSpeed: 0.012,
    axialTilt: 0.5,
    roughness: 0.85,
    metalness: 0.0,
    textures: { color: 'moon_color.jpg' },
    tint: 0xe8e8f0,
    atmosphere: { color: 0xaaccff, intensity: 0.4, scale: 1.15 },
    info: {
      type: 'Planeta anão',
      radiusKm: '1.163 km',
      mass: '1,66 × 10²² kg',
      temp: '-243 °C',
      funFact: 'Mais massivo que Plutão, fica a 3 vezes a distância de Netuno.',
    },
  },
];
